# Generated by Django 3.0.7 on 2020-10-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20201009_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerscompensationquoterequest',
            name='premium',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerscompensationquoterequest',
            name='quote_received',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
