# Generated by Django 3.0.7 on 2021-01-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0010_auto'),
        ('quote', '0003_auto_20201009_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLiabilityQuoteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=255)),
                ('communications_contact_name', models.CharField(max_length=255)),
                ('communications_phone_number', models.CharField(max_length=255)),
                ('communications_email', models.CharField(max_length=255)),
                ('mailing_address1', models.CharField(max_length=255)),
                ('mailing_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing_city', models.CharField(max_length=255)),
                ('mailing_state', models.CharField(max_length=255)),
                ('mailing_zip', models.CharField(max_length=255)),
                ('location_address1', models.CharField(max_length=255)),
                ('location_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(max_length=255)),
                ('location_state', models.CharField(max_length=255)),
                ('location_zip', models.CharField(max_length=255)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('total_employee_payroll', models.PositiveIntegerField()),
                ('number_of_owners', models.PositiveIntegerField()),
                ('legal_entity_code', models.CharField(max_length=255)),
                ('spectrum_class_code', models.CharField(max_length=255)),
                ('effective_date', models.DateField()),
                ('business_start_year', models.PositiveIntegerField()),
                ('bop_type_code', models.CharField(max_length=255)),
                ('annual_sales', models.PositiveIntegerField()),
                ('quote_received', models.BooleanField(default=False, editable=False)),
                ('premium', models.PositiveIntegerField(blank=True, null=True)),
                ('api_account', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_liability_quote_requests', to='pronym_api.ApiAccount')),
            ],
        ),
    ]
